ProjectCPAIEngine/Areas/CPAIMVC/Controllers/SchedulerCMCSController.cs
using com.pttict.engine.utility;
using Newtonsoft.Json;
using OfficeOpenXml;
using OfficeOpenXml.Drawing.Chart;
using ProjectCPAIEngine.Areas.CPAIMVC.Models;
using ProjectCPAIEngine.Areas.CPAIMVC.ViewModels;
using ProjectCPAIEngine.DAL.Entity;
using ProjectCPAIEngine.Model;
using ProjectCPAIEngine.Utilities;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace ProjectCPAIEngine.Areas.CPAIMVC.Controllers
{
    public class SchedulerCMCSController : BaseController
    {
        ShareFn _FN = new ShareFn();
        const string returnPage = "../web/MainBoards.aspx";

        private void initializeDropDownList(ref SchedulerCMCSViewModel model, string pType)
        {
            //model.vessel = DropdownServiceModel.getVehicle(pType == ConstantPrm.SYSTEMTYPE.CRUDE ? "SCH_C" : "SCH_P");
            //model.product = DropdownServiceModel.getProduct(pType == ConstantPrm.SYSTEMTYPE.CRUDE ? "MAT_CMCS" : "MAT_CMMT");
            //model.portName = DropdownServiceModel.getPortName(false, "", pType == ConstantPrm.SYSTEMTYPE.CRUDE ? "PORT_CMCS" : "PORT_CMMT");
            model.vessel = DropdownServiceModel.getVehicle("SCH_C");
            model.product = DropdownServiceModel.getProduct("MAT_CMCS");
            model.portName = DropdownServiceModel.getPortName(false, "", "PORT_CMCS");
            model.vesselActivity = DropdownServiceModel.getVesselActivity(pType, true, "--- Please Select ---");
        }

        public List<ButtonAction> ButtonListScheduler
        {
            get
            {
                if (Session["ButtonListScheduler"] == null) return null;
                else return (List<ButtonAction>)Session["ButtonListScheduler"];
            }
            set { Session["ButtonListScheduler"] = value; }
        }

        private void BindButtonPermission(List<ButtonAction> Button)
        {
            if (Request.QueryString["isDup"] == null)
            {
                ViewBag.ButtonMode = "MANUAL";
                if (Button.Where(x => x.name.ToUpper() == ConstantPrm.ACTION.SAVE_DRAFT).ToList().Count <= 0)
                {
                    ViewBag.PageMode = "READ";
                }
                foreach (ButtonAction _button in Button)
                {
                    string _btn = "<input type='submit' id='" + _button.name + "' value='" + _button.name + "' class='" + _FN.GetDefaultButtonCSS(_button.name) + "' onclick='OpenBoxBungerPrompt(\"" + _FN.GetMessageBTN(_button.name) + "\",\"" + _button.name + "\");return false;' />";
                    ViewBag.ButtonCode += _btn;
                }
                ViewBag.ButtonCode += "<input type='submit' value='MANUAL' id='btnMANUAL' style='display: none;' name='action:MANUAL' />";
                ButtonListScheduler = Button;
            }
            else
            {
                ViewBag.ButtonMode = "AUTO";
                ViewBag.PageMode = "EDIT";
            }
        }

        private void updateModel(FormCollection form, ref SchedulerCMCSViewModel model, bool isTextMode = false)
        {
            //Voyage Period
            if (!string.IsNullOrEmpty(model.schs_tempDateFrom) || !string.IsNullOrEmpty(model.schs_tempDateTo))
            {
                //model.schs_detail.date_start = model.schs_tempDateFrom;
                //model.schs_detail.date_end = model.schs_tempDateTo;
                model.schs_detail.date_start = model.schs_tempDateFrom.SplitWord(" ")[0] + " " + model.schs_tempDateFrom.SplitWord(" ")[1];
                model.schs_detail.date_end = model.schs_tempDateFrom.SplitWord(" ")[3] + " " + model.schs_tempDateFrom.SplitWord(" ")[4];
            }

            //Load Port
            if (model.schs_load_ports != null)
            {
                int i = 0;
                List<Model.SchsLoadPorts> schs_load_ports_list = new List<Model.SchsLoadPorts>();
                foreach (var v1 in model.schs_load_ports)
                {
                    Model.SchsLoadPorts schs_load_ports = new Model.SchsLoadPorts();
                    schs_load_ports.order = (i + 1).ToString();
                    schs_load_ports.port = v1.port;
                    List<Model.SchsCrude> schs_crude_list = new List<Model.SchsCrude>();
                    int j = 0;
                    foreach (var v2 in model.schs_load_ports[i].schs_crude)
                    {
                        Model.SchsCrude schs_crude = new Model.SchsCrude();
                        schs_crude.crude = v2.crude;
                        schs_crude.qty = v2.qty;
                        if (v2.nominate_date != null)
                        {
                            schs_crude.nominate_date_start = v2.nominate_date.SplitWord(" ")[0];
                            schs_crude.nominate_date_end = v2.nominate_date.SplitWord(" ")[2];

                        }
                        else
                        {
                            schs_crude.nominate_date_start = null;
                            schs_crude.nominate_date_end = null;
                        }
                        if (v2.received_date != null)
                        {
                            schs_crude.received_date_start = v2.received_date.SplitWord(" ")[0];
                            schs_crude.received_date_end = v2.received_date.SplitWord(" ")[2];
                        }
                        else
                        {
                            schs_crude.received_date_start = null;
                            schs_crude.received_date_end = null;
                        }

                        schs_crude_list.Add(schs_crude);
                        j++;
                    }
                    schs_load_ports.schs_crude = schs_crude_list;
                    schs_load_ports_list.Add(schs_load_ports);
                    i++;
                }
                model.schs_detail.schs_load_ports = schs_load_ports_list;
            }

            //DisPort
            if (model.schs_dis_ports != null)
            {
                List<Model.SchsDisPorts> schs_dis_ports_list = new List<Model.SchsDisPorts>();
                for (int i = 0; i < model.schs_dis_ports.Count; i++)
                {
                    Model.SchsDisPorts schs_dis_ports = new Model.SchsDisPorts();
                    schs_dis_ports.order = (i + 1).ToString();
                    schs_dis_ports.port = model.schs_dis_ports[i].port;
                    schs_dis_ports_list.Add(schs_dis_ports);
                }
                model.schs_detail.schs_dis_ports = schs_dis_ports_list;
            }
        }

        // GET: CPAIMVC/SchedulerCMCS
        public ActionResult Index()
        {
            Session["PageAction"] = "SCH"; // For _btn_Click
            string TranID = String.IsNullOrEmpty(Request.QueryString["TranID"]) ? null : Request.QueryString["TranID"].ToString().Decrypt();
            string Status = String.IsNullOrEmpty(Request.QueryString["Status"]) ? null : Request.QueryString["Status"].ToString().Decrypt(); // Status (DRAFT,SUBMIT,CANCEL)
            string Type = !string.IsNullOrEmpty(Request.QueryString["Type"]) ? Request.QueryString["Type"].ToString().Decrypt() : Session["Schedule_Type"] != null ? Session["Schedule_Type"].ToString().Decrypt() : "";
            string DocNO = String.IsNullOrEmpty(Request.QueryString["DocNO"]) ? null : Request.QueryString["DocNO"].ToString().Decrypt();
            string Tran_Req_ID = String.IsNullOrEmpty(Request.QueryString["Tran_Req_ID"]) ? null : Request.QueryString["Tran_Req_ID"].ToString().Decrypt();
            string isDup = String.IsNullOrEmpty(Request.QueryString["isDup"]) ? null : Request.QueryString["TranID"].ToString().Decrypt();

            SchedulerCMCSViewModel model = new SchedulerCMCSViewModel();
            //initializeDropDownList(ref model, null);

            if (TranID != null && Status != null)
            {
                // Get Data by TranID
                ResponseData resData = LoadDataSchedulerDetail(TranID, Type, ref model);
                // Set DDL
                initializeDropDownList(ref model, Type);

                // Set Alert Message
                if (resData != null && resData.result_code != "1")
                {
                    TempData["res_message"] = resData.response_message;
                }

                // Check is not Duplicate
                if (Request.QueryString["isDup"] == null)
                {
                    ViewBag.TaskID = TranID;    // Set Transaction ID

                    if (Status.ToUpper() == "DRAFT")
                    {
                        ViewBag.Title = "Edit schedule (DRAFT)";
                        ViewBag.PageMode = "EDIT";       //PageMode is EDIT or READ
                        ViewBag.ButtonMode = "MANUAL";    //ButtonMode is AUTO or MANUAL
                    }
                    else if (Status.ToUpper() == "SUBMIT")
                    {
                        ViewBag.Title = "Edit schedule (SUBMIT)";
                        ViewBag.PageMode = "EDIT";       //PageMode is EDIT or READ
                        ViewBag.ButtonMode = "MANUAL";    //ButtonMode is AUTO or MANUAL
                    }
                    else // CANCEL or Other
                    {
                        ViewBag.Title = "View schedule (CANCEL)";
                        ViewBag.PageMode = "READ";       //PageMode is EDIT or READ
                        ViewBag.ButtonMode = "MANUAL";    //ButtonMode is AUTO or MANUAL
                    }

                    // Set parameter not Encrypt
                    model.schs_Transaction_id = String.IsNullOrEmpty(TranID) ? null : TranID;
                    model.schs_Status = String.IsNullOrEmpty(Status) ? null : Status; // Status (DRAFT,SUBMIT,CANCEL)
                    model.schs_Type = String.IsNullOrEmpty(Type) ? null : Type;

ProjectCPAIEngine/Areas/CPAIMVC/Views/SchedulerCMCS/VesselUtilizationReport.cshtml
@model ProjectCPAIEngine.Areas.CPAIMVC.ViewModels.Vessel_Utilization_Report


<div class="wrapper-detail">
    <div>
        <h1 style="font-weight: bold;">Vessel Utilization</h1>
    </div>

    <div class="row">
        <div class="form-horizontal">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="col-md-3 control-label">Vessel Name</label>
                    <div class="col-md-8">
                        @Html.DropDownListFor(model => model.Search.sVessel, Model.Vessel, new { @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">

            </div>
        </div>
    </div>

    @using (Html.BeginForm("GenExcel", "SchedulerCMCS", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="row">
            <div class="form-horizontal">
                @Html.HiddenFor(model => model.Search.sVessel, new { id = "SearchsVesselTc" })
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Voyage No</label>
                        <div class="col-md-4">
                            @Html.TextBoxFor(model => model.Search.VoyageFrom, new { @class = "form-control" })
                        </div>
                        <label class="col-md-1 control-label">To</label>
                        <div class="col-md-4">
                            @Html.TextBoxFor(model => model.Search.VoyageTo, new { @class = "form-control" , @maxlength = "4" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-3">
                            <button type="button" onclick="funcSubmitTC()" class="btn">Excel</button>
                            <button id="btnExTC" type="submit" class="btn" style="display:none;">Excel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    @using (Html.BeginForm("GenExcel", "SchedulerCMCS", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="row">
            <div class="form-horizontal">
                @Html.HiddenFor(model => model.Search.sVessel, new { id = "SearchsVessel1" })
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Year</label>
                        <div class="col-md-4">
                            @Html.DropDownListFor(model => model.Search.sYearly, Model.Yearly, new { @class = "form-control" })
                        </div>
                        <div class="col-md-4">
                            <button type="submit" class="btn">Excel</button>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-3">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    }

    @using (Html.BeginForm("GenExcel", "SchedulerCMCS", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="row">
            <div class="form-horizontal">
                @Html.HiddenFor(model => model.Search.sVessel, new { id = "SearchsVessel2" })
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Monthly From</label>
                        <div class="col-md-4">
                            @Html.DropDownListFor(model => model.Search.sMonthlyFrom, Model.MonthlyFrom, new { @class = "form-control" })
                        </div>
                        <label class="col-md-1 control-label"></label>
                        <div class="col-md-4">
                            @Html.DropDownListFor(model => model.Search.sYearlyFrom, Model.YearlyFrom, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-md-2 control-label">Monthly To</label>
                        <div class="col-md-4">
                            @Html.DropDownListFor(model => model.Search.sMonthlyTo, Model.MonthlyTo, new { @class = "form-control" })
                        </div>
                        <div class="col-md-4">
                            @Html.DropDownListFor(model => model.Search.sYearlyTo, Model.YearlyTo, new { @class = "form-control" })
                        </div>
                        <div class="col-md-1">
                            <button type="submit" id="submit_mtm" class="btn">Excel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }


     
    @using (Html.BeginForm("GenExcel", "SchedulerCMCS", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div class="row">
            <div class="form-horizontal">
               @Html.HiddenFor(model => model.Search.sVessel, new { id = "SearchsVessel3" })
                <div class="col-md-6">
                    <div class="form-group">
                        <label class="col-md-3 control-label">Yearly Comparison</label>
                        <div class="col-md-4">
                            @Html.DropDownListFor(model => model.Search.sYearlyComparsion1, Model.YearlyComparsion1, new { @class = "form-control" })
                        </div>
                        <label class="col-md-1 control-label"></label>
                        <div class="col-md-4">
                            @Html.DropDownListFor(model => model.Search.sYearlyComparsion2, Model.YearlyComparsion1, new { @class = "form-control" })
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <div class="col-md-3">
                            <button type="submit" class="btn">Excel</button>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
    }


</div>


<script>
    $(function () {
        $('#SearchsVesselTc').val($('#Search_sVessel').val());
        $('#SearchsVessel1').val($('#Search_sVessel').val());
        $('#SearchsVessel2').val($('#Search_sVessel').val());
        $('#SearchsVessel3').val($('#Search_sVessel').val());
        if ($('#Search_sYearlyFrom').val() != $('#Search_sYearlyTo').val()) {
            debugger;

        }
    });
    $('#Search_sVessel').change(function () {
        debugger;
        $('#SearchsVesselTc').val($('#Search_sVessel').val());
        $('#SearchsVessel1').val($('#Search_sVessel').val());
        $('#SearchsVessel2').val($('#Search_sVessel').val());
        $('#SearchsVessel3').val($('#Search_sVessel').val());

    })
    var month_count = 0;
    var year_coount = 0;
    $('#Search_sYearlyFrom').change(function () {
        debugger;
        var y = $('#Search_sYearlyTo').val() - $('#Search_sYearlyFrom').val();
        if (y > 1) {
            alert('Over 24 Month')
            $("#submit_mtm").hide();
            alert('Please select month but not more than 24 months');
        } else if (y < 1) {
            alert('Not Format');
            $("#submit_mtm").hide();
        } else {
            $("#submit_mtm").show();
        }

    })
    $('#Search_sYearlyTo').change(function () {
        debugger;
        var y = $('#Search_sYearlyTo').val() - $('#Search_sYearlyFrom').val();
        if (y > 1) {
            alert('Over 24 Month');
            $("#submit_mtm").hide();
            alert('Please select month but not more than 24 months');
        } else if (y < 1) {
            alert('Not Format');
            $("#submit_mtm").hide();
        } else {
            $("#submit_mtm").show();
        }

    });

    function funcSubmitTC() {
        $("#Search_VoyageFrom").removeClass("input-error");
        $("#Search_VoyageTo").removeClass("input-error");
        var FocusCtrl = "";
        var chk = 0;
        if ($.trim($('#Search_VoyageFrom').val()) === '')
        {
            addValidMessageError($("#Search_VoyageFrom"), "Please input Value.");
            if (FocusCtrl == "") FocusCtrl = '#Search_VoyageFrom';
            chk++;
        }
        if ($.trim($('#Search_VoyageTo').val()) === '')
        {
            addValidMessageError($("#Search_VoyageTo"), "Please input Value.");
            if (FocusCtrl == "") FocusCtrl = '#Search_VoyageTo';
            chk++;
        }
        if(chk == 0)
        {
            $('#btnExTC').click();
        }
    };

</script>