ProjectCPAIEngine/Areas/CPAIMVC/ViewModels/HedgeAnnualViewModel.cs
using ProjectCPAIEngine.DAL.Entity;
using ProjectCPAIEngine.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectCPAIEngine.Areas.CPAIMVC.ViewModels
{
    public class HedgeAnnualViewModel
    {
        public static string FORMAT_DATE = "dd/MM/yyyy";
        public static string FORMAT_DATETIME = "dd/MM/yyyy HH:mm";

        // MAIN PROPERTIES //
        public string trading_book { get; set; }
        public string approved_date { get; set; }
        public string note { get; set; }
        public string attach_file { get; set; }

        public string update_by { get; set; }
        public string update_date { get; set; }
        public string status { get; set; }
        public string version { get; set; }

        public HedgAnnualSubmitNote hedge_annual_submit_note { get; set; } = new HedgAnnualSubmitNote();
        public List<HedgeAnnualTypeViewModel> hedge_annual_types { get; set; } = new List<HedgeAnnualTypeViewModel>();

        // DROPDOWN LIST PROPERTIES //
        public List<SelectListItem> ddlTrading { get; set; } = new List<SelectListItem>();
        public List<SelectListItem> ddlHedgeType { get; set; } = new List<SelectListItem>();
        public List<SelectListItem> ddlHedgeProduct { get; set; } = new List<SelectListItem>();
        public List<SelectListItem> ddlHedgeUnitPrice { get; set; } = new List<SelectListItem>();
        public List<SelectListItem> ddlHedgeUnitVolume { get; set; } = new List<SelectListItem>();
        public List<SelectListItem> ddlHedgeMinMax { get; set; } = new List<SelectListItem>();

        // INTERFACE PROPERTIES //
        public string hedge_type { get; set; }
        public string action { get; set; }

        public string taskID { get; set; }
        public string reqID { get; set; }
        public string purno { get; set; }
        public string pageMode { get; set; }
        public string buttonMode { get; set; }
        public string buttonCode { get; set; }

    }

    public class HedgeAnnualSubmitNoteViewModel {
        public string subject { get; set; }
        public string ref_no { get; set; }
        public string note { get; set; }
        public string attach_file { get; set; }
    }

    public class HedgeAnnualTypeViewModel {
        public string hedge_type { get; set; }
        public string hedge_type_name { get; set; }
        public string hedge_type_order { get; set; }
        public List<HedgeAnnualTypeDetailViewModel> hedge_annual_type_details { get; set; } = new List<HedgeAnnualTypeDetailViewModel>();
    }

    public class HedgeAnnualTypeDetailViewModel {
        public string key { get; set; }
        public string order { get; set; }
        public string product_front { get; set; }
        public string product_back { get; set; }
        public string title { get; set; }
        public string approved_date { get; set; }
        public string unit_price { get; set; }
        public string unit_volume { get; set; }
        public string year { get; set; }
        public string min_max { get; set; }
        public string price_year { get; set; }
        public string price_Q1 { get; set; }
        public string price_Q2 { get; set; }
        public string price_Q3 { get; set; }
        public string price_Q4 { get; set; }
        public string prod_volume { get; set; }
        public string limit_volume { get; set; }
        public string approved_volume { get; set; }
        public string note { get; set; }

        public string action { get; set; } = Utilities.ConstantPrm.ACTION.VIEW;
    }



    public class HedgeAnnualSearchViewModel
    {
        public string trading_book { get; set; }
        public string approved_date { get; set; }
        public string update_date { get; set; }
        public string update_by { get; set; }
        public string status { get; set; }
        public List<HedgeAnnualViewModel> hedge_annuals { get; set; } = new List<HedgeAnnualViewModel>();
        public List<HedgeAnnualEncrypt> HedgeAnnualTransaction { get; set; }


        public List<SelectListItem> ddlTrading { get; set; } = new List<SelectListItem>();
        public List<SelectListItem> ddlStatus { get; set; } = new List<SelectListItem>();

    }

    public class HedgeAnnualHistoryViewModel
    {
        public string tran_id { get; set; }
        public string trading_book { get; set; }
        public string approved_date { get; set; }
        public string version { get; set; }
        public string ref_no { get; set; }
        public string subject { get; set; }
        public string note { get; set; }
        public string update_date { get; set; }
        public string update_by { get; set; }
    }

    public class HedgeAnnualProductHistoryViewModel
    {
        public string product_front { get; set; }
        public string product_back { get; set; }
        public string title { get; set; }
        public string version { get; set; }
        public string approved_date { get; set; }
        public string unit_price { get; set; }
        public string unit_vol { get; set; }
        public string year { get; set; }
        public string min_max { get; set; }
        public string price_year { get; set; }
        public string price_q1 { get; set; }
        public string price_q2 { get; set; }
        public string price_q3 { get; set; }
        public string price_q4 { get; set; }
        public string prod_vol { get; set; }
        public string limit_vol { get; set; }
        public string approved_vol { get; set; }
        public string note { get; set; }
    }
    
}

ProjectCPAIEngine/Areas/CPAIMVC/Controllers/HedgeAnnualController.cs
using com.pttict.engine.utility;
using ProjectCPAIEngine.Areas.CPAIMVC.Models;
using ProjectCPAIEngine.Areas.CPAIMVC.ViewModels;
using ProjectCPAIEngine.DAL.DALBunker;
using ProjectCPAIEngine.Model;
using static ProjectCPAIEngine.Flow.Utilities.CPAIConstantUtil;
using ProjectCPAIEngine.Utilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using ProjectCPAIEngine.DAL.Entity;
using ProjectCPAIEngine.DAL.DALMaster;
using System.Globalization;
using ProjectCPAIEngine.DAL;
using com.pttict.engine.dal.Entity;
using System.IO;
using OfficeOpenXml;
using OfficeOpenXml.Style;

using DevExpress.Spreadsheet;

namespace ProjectCPAIEngine.Areas.CPAIMVC.Controllers
{
    public class HedgeAnnualController : BaseController
    {
        public HedgeAnnualSearchViewModel modelSearch
        {
            get { return TempData["HedgeAnnualSearchViewModel"] != null ? (HedgeAnnualSearchViewModel)TempData["HedgeAnnualSearchViewModel"] : new HedgeAnnualSearchViewModel(); }
            set { TempData["HedgeAnnualSearchViewModel"] = value; }
        }

        public HedgeAnnualViewModel modelView
        {
            get { return TempData["HedgeAnnualViewModel"] as HedgeAnnualViewModel; }
            set { TempData["HedgeAnnualViewModel"] = value; }
        }

        public List<ButtonAction> ButtonListHedgeAnnual
        {
            get
            {
                if (Session["ButtonListHedgeAnnual"] == null) return null;
                else return (List<ButtonAction>)Session["ButtonListHedgeAnnual"];
            }
            set { Session["ButtonListHedgeAnnual"] = value; }
        }

        ShareFn _FN = new ShareFn();
        const string returnPage = "/web/MainBoards.aspx";
        const string JSON_HEDG = "JSON_HEDG";

        // GET: CPAIMVC/HedgingFramework
        public ActionResult Index()
        {
            return RedirectToAction("Search");
        }

        public ActionResult Search()
        {
            HedgeAnnualSearchViewModel model;
            model = modelSearch;

            initializeDropDownList(ref model);
            return View(model);
        }


        public ActionResult Create()
        {
            HedgeAnnualViewModel model = new HedgeAnnualViewModel();
            if (modelView != null)
            {
                model = modelView;
                modelView = null;
            }
            model.pageMode = "EDIT";
            model.buttonMode = "AUTO";
            initializeDropDownList(ref model);
            return View(model);
        }

        public ActionResult Edit()
        {
            HedgeAnnualViewModel model = new HedgeAnnualViewModel();
            if (modelView == null)
            {
                if (Request.QueryString["TranID"] != null)
                {
                    string tranID = Request.QueryString["TranID"].ToString().Decrypt();
                    string reqID = Request.QueryString["Tran_Req_ID"].ToString().Decrypt();
                    ResponseData resData = LoadDataHedgeAnnual(tranID, ref model);
                    if (resData != null)
                    {
                        model.taskID = tranID;
                        model.reqID = reqID;
                        if (!(resData.result_code == "1" || resData.result_code == "2"))
                        {
                            TempData["res_message"] = string.IsNullOrEmpty(resData.response_message) ? resData.result_desc : resData.response_message;
                            TempData["returnPage"] = JSONSetting.getGlobalConfig("ROOT_URL") + returnPage;
                        }
                    }
                }
            }
            else
            {
                model = modelView;
                modelView = null;
            }
            model.pageMode = "EDIT";
            model.buttonMode = "MANUAL";
            initializeDropDownList(ref model);
            return View("Create", model);
        }

        public ActionResult History()
        {
            HedgeAnnualViewModel model = new HedgeAnnualViewModel();

            if (modelView == null)
            {
                model = new HedgeAnnualViewModel();
                if (Request.QueryString["TranID"] != null)
                {
                    string tranID = Request.QueryString["TranID"].ToString().Decrypt();
                    string reqID = Request.QueryString["Tran_Req_ID"].ToString().Decrypt();
                    ResponseData resData = LoadDataHedgeAnnual(tranID, ref model);
                    if (resData != null)
                    {
                        model.taskID = tranID;
                        model.reqID = reqID;
                        if (!(resData.result_code == "1" || resData.result_code == "2"))
                        {
                            TempData["res_message"] = string.IsNullOrEmpty(resData.response_message) ? resData.result_desc : resData.response_message;
                            TempData["returnPage"] = JSONSetting.getGlobalConfig("ROOT_URL") + returnPage;
                        }
                    }
                }
            }
            else
            {
                model = modelView;
                modelView = null;
            }
            model.pageMode = "READ";
            model.buttonMode = "AUTO";
            initializeDropDownList(ref model);
            return View("Create", model);
        }

        public ActionResult SearchResult(FormCollection fm, HedgeAnnualSearchViewModel model)
        {
            string approved_date_start = DateSplit(model.approved_date, true);
            string appruved_date_end = DateSplit(model.approved_date, false);
            string update_date_start = DateSplit(model.update_date, true);
            string update_date_end = DateSplit(model.update_date, false);

            var activationddl = getActivationStatus(isOnlyVisibility: true);
            List<string> sort_activation = new List<string>();
            foreach (var item in activationddl)
            {
                sort_activation.Add(item.Value);
            }

            string approved_date = !string.IsNullOrEmpty(approved_date_start) ? approved_date_start + "|" + appruved_date_end : "";
            string update_date = !string.IsNullOrEmpty(update_date_start) ? update_date_start + "|" + update_date_end : "";
            List_HedgeAnnualtrx res = SearchHedgeAnnualData(
                        company: model.trading_book,
                        approved_date: approved_date,
                        updated_date: update_date,
                        updated_by: model.update_by,
                        status: model.status
                );
            model.HedgeAnnualTransaction = res.HedgeAnnualTransaction.Where(x => sort_activation.Where(a => a == x.activation_status).Any()).OrderByDescending(y => y.transaction_id).ToList();
            foreach (var item in model.HedgeAnnualTransaction)
            {
                item.Transaction_id_Encrypted = item.transaction_id.Encrypt();
                item.Req_transaction_id_Encrypted = item.req_transaction_id.Encrypt();
            }

            modelSearch = model;
            return RedirectToAction("Search");
        }


        private List_HedgeAnnualtrx SearchHedgeAnnualData(string system = "", string type = "", string action = "", string status = "",
                                                          string create_by = "", string company = "", string version = "", string approved_date = "",
                                                          string activation_status = "", string updated_date = "", string updated_by = "")
        {
            RequestCPAI req = new RequestCPAI();
            req.Function_id = ConstantPrm.FUNCTION.F10000068;
            req.App_user = ConstantPrm.ENGINECONF.EnginAppID;
            req.App_password = ConstantPrm.ENGINECONF.EnginAppPassword;
            req.Req_transaction_id = ConstantPrm.EnginGetEngineID();

            req.Req_parameters = new Req_parameters();
            req.Req_parameters.P = new List<P>();
            req.Req_parameters.P.Add(new P { K = "channel", V = ConstantPrm.ENGINECONF.WEBChannel });
            req.Req_parameters.P.Add(new P { K = "user", V = lbUserID });
            req.Req_parameters.P.Add(new P { K = "system", V = ConstantPrm.SYSTEM.HEDG });
            req.Req_parameters.P.Add(new P { K = "page_number", V = "1" });
            req.Req_parameters.P.Add(new P { K = "rows_per_page", V = "20" });
            req.Req_parameters.P.Add(new P { K = "status", V = "" });
            req.Req_parameters.P.Add(new P { K = "from_date", V = "" });
            req.Req_parameters.P.Add(new P { K = "to_date", V = "" });
            req.Req_parameters.P.Add(new P { K = "function_code", V = HEDGE_ANNUAL_FUNCTION_CODE });
            req.Req_parameters.P.Add(new P { K = "index_1", V = ConstantPrm.SYSTEM.HEDG });
            req.Req_parameters.P.Add(new P { K = "index_2", V = ConstantPrm.SYSTEM.HEDG });
            req.Req_parameters.P.Add(new P { K = "index_9", V = create_by });
            req.Req_parameters.P.Add(new P { K = "index_10", V = company });
            req.Req_parameters.P.Add(new P { K = "index_11", V = version });
            req.Req_parameters.P.Add(new P { K = "index_12", V = approved_date });
            req.Req_parameters.P.Add(new P { K = "index_13", V = status });
            req.Req_parameters.P.Add(new P { K = "index_14", V = updated_date });
            req.Req_parameters.P.Add(new P { K = "index_15", V = updated_by });

            ResponseData resData = new ResponseData();
            RequestData reqData = new RequestData();
            ServiceProvider.ProjService service = new ServiceProvider.ProjService();

            var xml = ShareFunction.XMLSerialize(req);
            reqData = ShareFunction.DeserializeXMLFileToObject<RequestData>(xml);

ProjectCPAIEngine/Areas/CPAIMVC/Views/HedgeAnnual/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <div> 
    </div>
</body>
</html>

ProjectCPAIEngine/Areas/CPAIMVC/Views/HedgeAnnual/Search.cshtml
@model ProjectCPAIEngine.Areas.CPAIMVC.ViewModels.HedgeAnnualSearchViewModel
@{
    ViewBag.Title = "Annual Hedging Framework";
}

@using (Html.BeginForm("SearchResult", "HedgeAnnual", FormMethod.Post, new { @class = "form-horizontal", @name = "searchForm", @id = "searchForm" }))
{
    <div class="page-header">
        <h1>@ViewBag.Title</h1>
    </div>

    <div class="form-horizontal">
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="col-md-3 control-label">Trading Book</label>
                    <div class="col-md-6">
                        @Html.DropDownListFor(m => m.trading_book, new SelectList(Model.ddlTrading, "Value", "Text", Model.trading_book), "-- Select All --", new { @class = "form-control search-input" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="col-md-3 control-label">Approved Date</label>
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.approved_date, new { @class = "form-control input-date-picker search-input", @placeholder = "DD/MM/YYYY to DD/MM/YYYY", @maxlength = "26" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="col-md-3 control-label">Update Date</label>
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.update_date, new { @class = "form-control input-date-picker search-input", @placeholder = "DD/MM/YYYY to DD/MM/YYYY", @maxlength = "26" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="col-md-3 control-label">Update By</label>
                    <div class="col-md-6">
                        @Html.TextBoxFor(m => m.update_by, new { @class = "form-control search-input" })
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="col-md-3 control-label">Status</label>
                    <div class="col-md-6">
                        @Html.DropDownListFor(m => m.status, new SelectList(Model.ddlStatus, "Value", "Text", Model.status), "-- Select All --", new { @class = "form-control search-input" })
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="form-group">
            <div class="pull-left">
                @Html.ActionLink("New", "Create", new { controller = "HedgeAnnual" }, new { @class = "btn btn-success" })
            </div>
        <center>
            <button style="margin-left: -100px;" type="submit" class="btn btn-primary">Search</button>
            <button type="button" class="btn btn-default" onclick="clear_input()">Clear All</button>
        </center>
    </div>
}

<div class="page-header">
    <h1>Search Result</h1>
</div>

<table id="searchResultTable" class="table table-hover display" cellspacing="0">
    <thead>
        <tr>
            <th>Trading Book</th>
            <th>Approved Date</th>
            <th>Status</th>
            <th>Version</th>
            <th>Update Date</th>
            <th>Update By</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.HedgeAnnualTransaction != null && Model.HedgeAnnualTransaction.Any())
        {
            foreach (var item in Model.HedgeAnnualTransaction)
            {
                <tr>
                    <td>@item.company</td>
                    <td>@item.approved_date</td>
                    <td>@item.activation_status</td>
                    <td>@item.version</td>
                    <td>@item.updated_date</td>
                    <td>@item.updated_by</td>
                    <td>
                        @if (item.activation_status == "DRAFT")
                                        {
                            <a href="../HedgeAnnual/Edit?TranID=@item.Transaction_id_Encrypted&Tran_Req_ID=@item.Req_transaction_id_Encrypted"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        }
                        else if (item.latest_version == "Y")
                        {
                            <a href="../HedgeAnnual/Edit?TranID=@item.Transaction_id_Encrypted&Tran_Req_ID=@item.Req_transaction_id_Encrypted"><i class="fa fa-pencil" aria-hidden="true"></i></a>
                        }
                        @if(item.activation_status != "DRAFT")
                        {
                            <a href="javascript:void(0);" onclick="get_history('@item.Transaction_id_Encrypted');"><i class="fa fa-file-text-o" data-toggle="modal" data-target=".bs-example-modal-lg"></i></a>
                        }
                    </td>
                </tr>
            }
        }
    </tbody>
</table>

<!-- Large modal -->
@*<button type="button" class="btn btn-primary" data-toggle="modal" data-target=".bs-example-modal-lg">Large modal</button>*@

<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
    <div class="modal-dialog modal-lg" role="document">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Annual Hedging Framework History</h4>
            </div>
            <div class="modal-body">
                <table id="searchResultHistoryTable" class="table table-hover display" cellspacing="0">
                    <thead>
                        <tr>
                            <th>Trading Book</th>
                            <th>Approved Date</th>
                            <th>Version</th>
                            <th>Reference No.</th>
                            <th>Subject</th>
                            <th>Note</th>
                            <th>Updated Date</th>
                            <th>Updated By</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">OK</button>
            </div>
        </div>
    </div>
</div>

<script>

    var table = $('#searchResultHistoryTable').DataTable({
        "scrollCollapse": false,
        "orderable": false,
        "bSort": false,
        "searching": false,
        "paging": false,
        "sDom": '<"top">rt<"bottom"flp><"clear">'
    });

    $(document).ready(function () {
        $('#searchResultTable').DataTable({
            "columnDefs": [
                {
                    "targets": [2],
                    "orderable": false
                }
            ],
            "scrollCollapse": true,
            "orderable": false,
            "bSort": false,
        });
    });

    $('#approved_date').dateRangePicker(
        {
            autoClose: true,
            singleDate: false,
            showShortcuts: false,
            format: 'DD/MM/YYYY',
            time: { enabled: false }
        });
    $('#update_date').dateRangePicker(
        {
            autoClose: true,
            singleDate: false,
            showShortcuts: false,
            format: 'DD/MM/YYYY',
            time: { enabled: false }
        });

    function clear_input() {
        $(".search-input").val("");
    }

    function get_history(tran_id) {
        $.ajax({
            url: '@Url.Action("GetHistory", "HedgeAnnual")',
            data: { "tranID": tran_id},
                cache: false,
                type: "GET",
                success: function (data) {
                    var markup = "";
                    for (var i = 0; i < data.length; i++) {
                        markup += '<tr class="drafts">';
                        markup += '<td>' + data[i].trading_book + '</td>';
                        markup += '<td>' + data[i].approved_date + '</td>';
                        markup += '<td><a href="../HedgeAnnual/History?TranID=' + data[i].tran_id + '&Tran_Req_ID=" target="_blank">' + data[i].version + '</a></td>';
                        markup += '<td>' + data[i].ref_no + '</td>';
                        markup += '<td>' + data[i].subject + '</td>';
                        markup += '<td>' + data[i].note + '</td>';
                        markup += '<td>' + data[i].update_date + '</td>';
                        markup += '<td>' + data[i].update_by + '</td>';
                        markup += '</tr>';
                    }
                    var table = $('#searchResultHistoryTable').DataTable();
                    table.rows().remove().draw();
                    table.rows.add($(markup)).draw();
                },
                error: function (reponse) {
                    var table = $('#searchResultHistoryTable').DataTable();
                    table.rows().remove().draw();
                    alert("error : " + reponse.error());
                }
            });
    }
</script>