ProjectCPAIEngine/Areas/CPAIMVC/ViewModels/ReverseFIDocumentViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjectCPAIEngine.Areas.CPAIMVC.ViewModels
{
    public class ReverseFIDocumentViewModel
    {
        public string Document { get; set; }
        public string ComCode { get; set; }
        public string Year { get; set; }

        public List<SelectListItem> ddl_Company { get; set; }
    }

    public class ReverseFIDocumentResult
    {
        public bool Pass { get; set; }
        public string PoNo { get; set; }
        public string SAPReverseDocNo { get; set; }
        public string ResultMessage { get; set; }
        public string CompanyCode { get; set; }

    }
}

ProjectCPAIEngine/Areas/CPAIMVC/Controllers/ReverseFIDocumentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectCPAIEngine.Areas.CPAIMVC.Models;
using ProjectCPAIEngine.Areas.CPAIMVC.ViewModels;
using com.pttict.sap.Interface.Service;
using com.pttict.engine.utility;
using ProjectCPAIEngine.Utilities;

namespace ProjectCPAIEngine.Areas.CPAIMVC.Controllers
{
    public class ReverseFIDocumentController : BaseController
    {
        // GET: CPAIMVC/ReverseFIDocument
        public ActionResult Index()
        {
            ReverseFIDocumentServiceModel serviceModel = new ReverseFIDocumentServiceModel();
            ReverseFIDocumentViewModel model = new ReverseFIDocumentViewModel();
            model.ddl_Company = serviceModel.GetCompany();

            return View(model);
        }

        public ActionResult PCF()
        {
            ReverseFIDocumentServiceModel serviceModel = new ReverseFIDocumentServiceModel();
            ReverseFIDocumentViewModel model = new ReverseFIDocumentViewModel();
            model.ddl_Company = serviceModel.GetCompany();

            return View("Index_PCF", model);
        }

        public ActionResult Search(ReverseFIDocumentViewModel model)
        {
            ReverseFIDocumentServiceModel service = new ReverseFIDocumentServiceModel();
            PurchaseEntryViewModel_Search purchaseEntryViewModel = new PurchaseEntryViewModel_Search();
            var searchModel = service.Search(model.Year, model.Document.Trim());
            Session["FIModel"] = model;

            return View("Search", searchModel);
        }

        public ActionResult Search_PCF(ReverseFIDocumentViewModel model)
        {
            var type = Request["ddlType"];

            if(type == "PPT")
            {
                ReverseFIDocumentServiceModel service = new ReverseFIDocumentServiceModel();
                PCFPurchaseEntryViewModel_Search purchaseEntryViewModel = new PCFPurchaseEntryViewModel_Search();
                var searchModel = service.SearchPCFTrain(model.Year, model.Document);
                Session["FIModel"] = model;

                return View("Search_Train", searchModel);
            }
            else if(type == "PPV")
            {
                ReverseFIDocumentServiceModel service = new ReverseFIDocumentServiceModel();
                PCFPurchaseEntryViewModel_Search purchaseEntryViewModel = new PCFPurchaseEntryViewModel_Search();
                var searchModel = service.SearchPCFVessel(model.Year, model.Document);
                Session["FIModel"] = model;

                return View("Search_Vessel", searchModel);
            }

            return View("Index_PCF");
        }

        public ActionResult Send(PurchaseEntryViewModel_SearchData data)
        {
            ReverseFIDocumentSendResult returnResult = new ReverseFIDocumentSendResult();
            ReverseFIDocumentViewModel model = new ReverseFIDocumentViewModel();
            ReverseFIDocumentServiceModel serviceModel = new ReverseFIDocumentServiceModel();

            if (Session["FIModel"] != null)
            {
                model = (ReverseFIDocumentViewModel)Session["FIModel"];
                returnResult = serviceModel.Post(model.Year, model.ComCode, model.Document);
            }
            else
            {
                model.ddl_Company = serviceModel.GetCompany();
                return View("Index", model);
            }

            ReverseFIDocumentResult result = new ReverseFIDocumentResult();
            result.Pass = returnResult.Pass;
            result.PoNo = data.PoNo;
            result.SAPReverseDocNo = returnResult.ReturnDocumentNo;
            result.ResultMessage = returnResult.ResultText;
            result.CompanyCode = model.ComCode;

            if (result.Pass)
            {
                serviceModel.UpdateTables(data, model.Document, result.SAPReverseDocNo, result);
            }
            
            return View("Result", result);
        }

        public ActionResult SendPCFTrain(PCFPurchaseEntryViewModel_SearchData Temp)
        {
            System.Globalization.CultureInfo provider = new System.Globalization.CultureInfo("en-US");
            string format = "dd/MM/yyyy";
            ReverseFIDocumentSendResult returnResult = new ReverseFIDocumentSendResult();
            ReverseFIDocumentViewModel model = new ReverseFIDocumentViewModel();
            ReverseFIDocumentServiceModel serviceModel = new ReverseFIDocumentServiceModel();
                
            if (Session["FIModel"] != null)
            {
                model = (ReverseFIDocumentViewModel)Session["FIModel"];
                returnResult = serviceModel.Post(model.Year, model.ComCode, model.Document);
            }
            else
            {
                model.ddl_Company = serviceModel.GetCompany();
                return View("Index_PCF", model);
            }

            ReverseFIDocumentResult result = new ReverseFIDocumentResult();
            result.Pass = returnResult.Pass;
            result.SAPReverseDocNo = returnResult.ReturnDocumentNo;
            result.ResultMessage = returnResult.ResultText;

            if (result.Pass)
            {
                string tripNo = Temp.TripNo;
                string MatItemNo = Temp.MatItemNo;
                string ItemNo = Temp.sOutturn[0].ItemNo;
                DateTime PODate = DateTime.ParseExact(Temp.sOutturn[0].BLDate,format,provider);
                serviceModel.UpdateTablesPCFTrain(tripNo, model.Document, result.SAPReverseDocNo, MatItemNo, ItemNo, PODate);
            }

            return View("Result_Train", result);
        }

        public ActionResult SendPCFVessel(PurchaseEntryVesselViewModel Temp)
        {
            ReverseFIDocumentSendResult returnResult = new ReverseFIDocumentSendResult();
            ReverseFIDocumentViewModel model = new ReverseFIDocumentViewModel();
            ReverseFIDocumentServiceModel serviceModel = new ReverseFIDocumentServiceModel();

            if (Session["FIModel"] != null)
            {
                model = (ReverseFIDocumentViewModel)Session["FIModel"];
                returnResult = serviceModel.Post(model.Year, model.ComCode, model.Document);
            }
            else
            {
                model.ddl_Company = serviceModel.GetCompany();
                return View("Index_PCF", model);
            }

            ReverseFIDocumentResult result = new ReverseFIDocumentResult();
            result.Pass = returnResult.Pass;
            result.SAPReverseDocNo = returnResult.ReturnDocumentNo;
            result.ResultMessage = returnResult.ResultText;

            if (result.Pass)
            {
                string tripNo = Temp.PriceList[0].sTripNo;
                string MatItemNo = Temp.PriceList[0].sMetNum;
                string ItemNo = Temp.PriceList[0].sItemNo;
                serviceModel.UpdateTablesPCFVessel(tripNo, Temp.PriceList[0].SAPDocumentNO, result.SAPReverseDocNo, MatItemNo, ItemNo);
            }
            return View("Result_Train", result);
        }
    }
}

ProjectCPAIEngine/Areas/CPAIMVC/Views/ReverseFIDocument/Index.cshtml
@model ProjectCPAIEngine.Areas.CPAIMVC.ViewModels.ReverseFIDocumentViewModel
@{
    ViewBag.Title = "Reverse FI Document";    
}


@using (Html.BeginForm("Search", "ReverseFIDocument", FormMethod.Post, new { @class = "form-horizontal" }))
{    
    <div class="page-header">
        <h1>Reverse FI Document for Intercompany</h1>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="form-group">
                <label class="control-label col-sm-2">Fiscal Year:</label>
                <div class="col-sm-3">
                    @Html.TextBoxFor(model => model.Year, htmlAttributes: new { @class = "form-control", @required = "required" })                    
                </div>
                <label class="control-label col-sm-2">Company:</label>
                <div class="col-sm-3">
                    @Html.DropDownListFor(model => model.ComCode, new SelectList(Model.ddl_Company, "Value", "Text"), "-- Select --", new { @class = "form-control", @Id = "ddlCompany", @required = "required" })
                    @*@Html.TextBoxFor(model => model.ComCode, htmlAttributes: new { @class = "form-control" })*@
                </div>                
            </div>
            <div class="form-group">
                <label class="control-label col-sm-2">FI Document No:</label>
                <div class="col-sm-3">
                    @Html.TextBoxFor(model => model.Document, new { @class = "form-control", @Id = "document", @required = "required" })
                </div>
                @*<label class="control-label col-sm-2">Type:</label>
                <div class="col-sm-3">
                    <select id="ddlType" name="ddlType" class="form-control">
                        <option value="IPE">Intercompany Purchase Entry</option>
                        <option value="PPT">PCF Purchase Entry - Train</option>
                        <option value="PPV">PCF Purchase Entry - Vessel</option>
                    </select>
                </div>*@
            </div>

            <div class="form-group">
                <div class="pull-left">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
                <div class="pull-right">
                </div>
            </div>
        </div>
    </div>
        
}

ProjectCPAIEngine/Areas/CPAIMVC/Views/ReverseFIDocument/Index_PCF.cshtml
@model ProjectCPAIEngine.Areas.CPAIMVC.ViewModels.ReverseFIDocumentViewModel
@{
    ViewBag.Title = "Reverse FI Document";
}

<div id="divSearch">
    @using (Html.BeginForm("Search_PCF", "ReverseFIDocument", FormMethod.Post, new { @class = "form-horizontal" }))
    {

        <div class="page-header">
            <h1>Reverse FI Document for Purchase Entry</h1>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="form-group">
                    <label class="control-label col-sm-2">Fiscal Year:</label>
                    <div class="col-sm-3">
                        @Html.TextBoxFor(model => model.Year, htmlAttributes: new { @class = "form-control", @required = "required" })
                    </div>
                    <label class="control-label col-sm-2">Company:</label>
                    <div class="col-sm-3">
                        @Html.DropDownListFor(model => model.ComCode, new SelectList(Model.ddl_Company, "Value", "Text"), "-- Select --", new { @class = "form-control", @Id = "ddlCompany", @required = "required" })
                        @*@Html.TextBoxFor(model => model.ComCode, htmlAttributes: new { @class = "form-control" })*@
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2">FI Document No:</label>
                    <div class="col-sm-3">
                        @Html.TextBoxFor(model => model.Document, new { @class = "form-control", @Id = "document", @required = "required" })
                    </div>
                    <label class="control-label col-sm-2">Type:</label>
                        <div class="col-sm-3">
                            <select id="ddlType" name="ddlType" class="form-control">
                                <option value="PPT">Purchase Entry - Train</option>
                                <option value="PPV">Purchase Entry - Vessel</option>
                            </select>
                        </div>
                </div>

                <div class="form-group">
                    <div class="pull-left">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                    <div class="pull-right">
                    </div>
                </div>
            </div>
        </div>

    }
</div>

ProjectCPAIEngine/Areas/CPAIMVC/Views/ReverseFIDocument/Result.cshtml
@model ProjectCPAIEngine.Areas.CPAIMVC.ViewModels.ReverseFIDocumentResult
@{
    ViewBag.Title = "Result";
}

@using (Html.BeginForm("Index", "ReverseFIDocument", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="page-header">
        <h1>Result</h1>
    </div>
    <div class="col-md-12">
        @if (Model.Pass)
        {
            <div class="form-group">
                <label class="control-label col-sm-2">Reversed Document No.:</label>
                <div class="col-sm-2">
                    @Html.DisplayTextFor(model => model.SAPReverseDocNo)
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                <label class="control-label col-sm-4">Error - @Model.ResultMessage</label>
            </div>
        }

        <div class="form-group">
            <div class="pull-left">
                <button type="submit" class="btn btn-primary">Back</button>
            </div>
            <div class="pull-right">
            </div>
        </div>
    </div>
}

ProjectCPAIEngine/Areas/CPAIMVC/Views/ReverseFIDocument/Result_Train.cshtml
@model ProjectCPAIEngine.Areas.CPAIMVC.ViewModels.ReverseFIDocumentResult
@{
    ViewBag.Title = "Result";
}

@using (Html.BeginForm("PCF", "ReverseFIDocument", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="page-header">
        <h1>Result</h1>
    </div>
    <div class="col-md-12">
        @if (Model.Pass)
        {
            <div class="form-group">
                <label class="control-label col-sm-2">Revised Document No.:</label>
                <div class="col-sm-2">
                    @Html.DisplayTextFor(model => model.SAPReverseDocNo)
                </div>
            </div>
        }
        else
        {
            <div class="form-group">
                <label class="control-label col-sm-4">Error - @Model.ResultMessage</label>
            </div>
        }

        <div class="form-group">
            <div class="pull-left">
                <button type="submit" class="btn btn-primary">Back</button>
            </div>
            <div class="pull-right">
            </div>
        </div>
    </div>
}

ProjectCPAIEngine/Areas/CPAIMVC/Views/ReverseFIDocument/Search.cshtml
@model ProjectCPAIEngine.Areas.CPAIMVC.ViewModels.PurchaseEntryViewModel_SearchData
@{
    ViewBag.Title = "Data Confirmation for Reverse FI Document";
    bool foundResult = false;
    if(!String.IsNullOrEmpty(Model.PoNo))
    {
        foundResult = true;
    }
}

<div id="divDataConfirmation">
    @using (Html.BeginForm("Send", "ReverseFIDocument", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div id="divPurchaseOrder">
            <h1>Data Confirmation for Reverse FI Document</h1>
            <h2>Purchase Order</h2>
            <table id="tblHeader" class="table">
                <thead>
                    <tr>
                        <th>Trip No.</th>
                        <th>PO No.</th>
                        <th>PO Date</th>
                        <th>Product</th>
                        <th>Supplier</th>
                        <th>Incoterms</th>
                        <th>Volume</th>
                        <th>Vol. Unit</th>
                        <th>Price</th>
                        <th>Total</th>
                        <th>Currency</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>@Model.TripNo</td>
                        <td>
                            @Model.PoNo
                            @Html.HiddenFor(x => x.PoNo)
                            @Html.HiddenFor(x => x.PoItem)
                            @Html.HiddenFor(x => x.PoDate)
                        </td>
                        <td>@Model.PoDate</td>
                        <td>@Model.Product</td>
                        <td>@Model.Supplier</td>
                        <td>@Model.Incoterms</td>
                        <td>@Model.Volume</td>
                        <td>@Model.VolumeUnit</td>
                        <td>@Model.Price</td>
                        <td>@Model.Total</td>
                        <td>@Model.Currency</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="divPurchaseEntry" style="overflow:auto">
            <h2>Purchase Entry</h2>
            <table class="table">
                <thead>
                    <tr>                        
                        <th rowspan="2">No.</th>
                        <th colspan="4">Bill of Lading (B/L)</th>
                        <th colspan="4">Goods Received - Outturn</th>
                        <th rowspan="2">Price</th>
                        <th rowspan="2">ROE</th>
                        <th rowspan="2">Amount USD</th>
                        <th rowspan="2">Amount THB</th>
                        <th rowspan="2">VAT 7% THB</th>
                        <th rowspan="2">Total Amount USD</th>
                        <th rowspan="2">Total Amount THB</th>
                        <th rowspan="2">SAP FI Doc.</th>
                        <th rowspan="2">SAP FI Doc. Status</th>
                        <th rowspan="2">Last Updated</th>
                        <th rowspan="2">Updated By</th>
                    </tr>
                    <tr>
                        <th>Date</th>
                        <th>Volume (BBL)</th>
                        <th>Volume (MT)</th>
                        <th>Volume (L30)</th>
                        <th>Date</th>
                        <th>Volume (BBL)</th>
                        <th>Volume (MT)</th>
                        <th>Volume (L30)</th>
                    </tr>
                </thead>
                <tbody>

                    @if (Model.sOutturn != null)
                    {
                        for (int idx = 0; idx < Model.sOutturn.Count(); idx++)
                        {
                            <tr>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].ItemNo)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].BLDate)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].BlQtyBbl)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].BlQtyMt)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].BlQtyMl)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].PostingDate)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].QtyBbl)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].QtyMt)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].QtyMl)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].Price)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].ROE)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].AmountUSD)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].AmountTHB)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].Vat7)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].TotalAmountUSD)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].TotalAmountTHB)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].SAPFIDoc)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].SAPFIDocStatus)</td>
                                <td nowrap>@Html.DisplayTextFor(model => model.sOutturn[idx].UpdatedDate)</td>
                                <td nowrap>
                                    @Html.DisplayTextFor(model => model.sOutturn[idx].UpdatedBy)
                                    @Html.HiddenFor(x => x.sOutturn[idx].ItemNo)
                                </td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <br />
        <div id="divButton">
            @if(foundResult)
            {
                <input type="submit" class="btn btn-primary" value="Reverse" />
            }
                <input type="button" class="btn btn-primary" value="Back" onclick="window.history.back()" />
        </div>
    }
</div>

ProjectCPAIEngine/Areas/CPAIMVC/Views/ReverseFIDocument/Search_Train.cshtml
@model ProjectCPAIEngine.Areas.CPAIMVC.ViewModels.PCFPurchaseEntryViewModel_SearchData
@{
    ViewBag.Title = "Data Confirmation for Reverse FI Document";
    bool foundResult = false;
    if (!String.IsNullOrEmpty(Model.TripNo))
    {
        foundResult = true;
    }
}

<div id="divDataConfirmation">
    @using (Html.BeginForm("SendPCFTrain", "ReverseFIDocument", FormMethod.Post, new { @class = "form-horizontal" }))
    {
        <div id="divPurchaseOrder">
            <h1>Data Confirmation for Reverse FI Document</h1>
            <h2>Purchase Order</h2>
            <table id="tblHeader" class="table">
                <thead>
                    <tr>
                        <th>Trip No.</th>
                        <th>Vessel</th>
                        <th>PO No.</th>
                        <th>Crude/Feedstock/Product</th>
                        <th>Supplier</th>
                        <th>QTY (KBBL)</th>
                        <th>QTY (KMT)</th>
                        <th>Purchase Type</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            @Html.DisplayTextFor(model => model.TripNo)
                            @Html.HiddenFor(x => x.TripNo)
                            @Html.HiddenFor(x => x.MatItemNo)
                        </td>
                        <td>@Model.Vessel</td>
                        <td>@Model.PoNo</td>
                        <td>@Model.Crude</td>
                        <td>@Model.Supplier</td>
                        <td>@Model.VolumeBBL</td>
                        <td>@Model.VolumeMT</td>
                        <td>@Model.PurchaseType</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div id="divPurchaseEntry" style="overflow:auto">
            <h2>PCF Purchase Entry - Train</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th rowspan="2">No.</th>
                        <th colspan="4">Bill of Lading (B/L)</th>
                        <th colspan="4">Goods Received - Outturn</th>
                        <th rowspan="2">FOB Price</th>
                        <th rowspan="2">Freight Price</th>
                        <th rowspan="2">C & F Price</th>
                        <th rowspan="2">ROE</th>
                        <th rowspan="2">FOB Amount USD</th>
                        <th rowspan="2">FOB Amount THB</th>
                        <th rowspan="2">Freight Amount USD</th>
                        <th rowspan="2">Freight Amount THB</th>
                        <th rowspan="2">C & F Amount USD</th>
                        <th rowspan="2">C & F Amount THB</th>
                        <th rowspan="2">C & F VAT 7% THB</th>
                        <th rowspan="2">C & F Total Amount USD</th>
                        <th rowspan="2">C & F Total Amount THB</th>
                        <th rowspan="2">SAP FI Doc.</th>
                        <th rowspan="2">SAP FI Doc. Status</th>
                        <th rowspan="2">Last Updated</th>
                        <th rowspan="2">Updated By</th>
                    </tr>
                    <tr>
                        <th>Date</th>
                        <th>Volume (BBL)</th>
                        <th>Volume (MT)</th>
                        <th>Volume (L30)</th>
                        <th>Date</th>
                        <th>Volume (BBL)</th>
                        <th>Volume (MT)</th>
                        <th>Volume (L30)</th>
                    </tr>
                </thead>
                <tbody>

                    @if (Model.sOutturn != null)
                    {
                        for (int idx = 0; idx < Model.sOutturn.Count(); idx++)
                        {
                            <tr>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].ItemNo)
                                @Html.HiddenFor(model => model.sOutturn[idx].ItemNo)
                                @Html.HiddenFor(model => model.sOutturn[idx].BLDate)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].BLDate)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].BlQtyBbl)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].BlQtyMt)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].BlQtyMl)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].PostingDate)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].QtyBbl)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].QtyMt)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].QtyMl)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].FOBPrice)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].FreightPrice)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].CnFPrice)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].ROE)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].FOBAmountUSD)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].FOBAmountTHB)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].FreightAmountUSD)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].FreightAmountTHB)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].CnFAmountUSD)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].CnFAmountTHB)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].CnFVat7)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].CnFTotalAmountUSD)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].CnFTotalAmountTHB)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].SAPFIDoc)</td>
                                <td>@Html.DisplayTextFor(model => model.sOutturn[idx].SAPFIDocStatus)</td>
                                <td nowrap>@Html.DisplayTextFor(model => model.sOutturn[idx].UpdatedDate)</td>
                                <td nowrap>@Html.DisplayTextFor(model => model.sOutturn[idx].UpdatedBy)</td>
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>
        <br />
        <div id="divButton">
            @if (foundResult)
            {
                <input type="submit" class="btn btn-primary" value="Reverse" />
            }
            <input type="button" class="btn btn-primary" value="Back" onclick="window.history.back()" />
        </div>
    }
</div>